spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: org.hibernate.dialect.PostgreSQL9Dialect
    url: jdbc:postgresql://localhost:5432/profiles_hw_19
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true
    url: jdbc:postgresql://localhost:5432/profiles_hw_19
    password: postgres
    check-location: false
    locations: classpath:db/migration
    username: postgres
    schemas: public